name: pharma_bros_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  logger: ^2.3.0
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: notosanskr
      fonts:
        - asset: assets/font/NotoSansKR-black.otf
          weight: 900
        - asset: assets/font/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/font/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/font/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/font/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/font/NotoSansKR-Thin.otf
          weight: 100